FROM golang:1.25 AS building

COPY . /building
WORKDIR /building

ARG GO111MODULE
ARG GOPROXY

ENV GO111MODULE=${GO111MODULE:+$GO111MODULE}
ENV GOPROXY=${GOPROXY:+$GOPROXY}

RUN make frpc

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]
