FROM golang:1.24 AS building

COPY . /building
WORKDIR /building

ARG GO111MODULE
ARG GOPROXY

ENV GO111MODULE=${GO111MODULE:+$GO111MODULE}
ENV GOPROXY=${GOPROXY:+$GOPROXY}

RUN make frps

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
